# -*- coding: utf-8 -*-
"""HOG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-jhTkxPKxZuEHyGS1Alb9zx1E1zwyuc
"""

# Commented out IPython magic to ensure Python compatibility.
# import the necessary packages
import matplotlib.pyplot as plt

from skimage.feature import hog
from skimage import exposure

# %matplotlib inline

# Dalal and Triggs report that using either 2 x 2 or 3 x 3  cells_per_block  obtains reasonable accuracy in most cases.
file  ="/content/Picture1.jpg"
image = plt.imread(file)

fd, hog_image = hog(image, orientations=15, pixels_per_cell=(10, 10),
                    cells_per_block=(1, 1), visualize=True, block_norm="L1", transform_sqrt=False)
# display the image
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

# Rescale histogram for better display
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 5))
# display the HOG features
ax2.axis('off')
ax2.imshow(hog_image_rescaled, cmap=plt.cm.gray)
ax2.set_title('Histogram of Oriented Gradients')